// Copyright 2026 Alexandre Santos and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPtCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pt",
		Short:       "List and get pt",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPtGetConfigurationCmd(flags))
	cmd.AddCommand(newPtGetOpenDetailGalleryCmd(flags))
	cmd.AddCommand(newPtListAdContactInfoForDetailAjaxCmd(flags))
	cmd.AddCommand(newPtListHomeCmd(flags))
	cmd.AddCommand(newPtListPagerCmd(flags))
	cmd.AddCommand(newPtListUserSearchesCmd(flags))
	return cmd
}
