// Copyright 2026 Alexandre Santos and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"
	"idealista-pp-cli/internal/store"
)

func newSearchCmd(flags *rootFlags) *cobra.Command {
	var resourceType string
	var limit int
	var dbPath string

	cmd := &cobra.Command{
		Use:   "search [query]",
		Short: "Search local data or use explicit website-native search helpers",
		Long: `Search has two modes in this CLI:

  1. Local full-text search over synced SQLite data
  2. Explicit website-native helpers for location lookup, saved-search state,
     and validated result URL composition

There is no supported generic live website search API. The public-site search
flow is path-shaped and session-backed, so live use must go through the
explicit subcommands instead of a free-text API query.`,
		Example: `  # Local FTS only
  idealista-pp-cli search "lisboa" --data-source local
  idealista-pp-cli search local "lisboa"

  # Website-native helpers
  idealista-pp-cli search locations lisboa
  idealista-pp-cli search saved
  idealista-pp-cli search results-url --location-path comprar-casas/lisboa/arroios --min-price 220000 --max-price 750000 --min-size 60 --max-size 120 --bedrooms t2,t3 --bathrooms 2,3 --amenities elevador,garagem
  idealista-pp-cli listing photos 34998327`,
		Annotations: map[string]string{"mcp:hidden": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			query := strings.Join(args, " ")
			if flags.dataSource != "local" {
				return usageErr(fmt.Errorf("generic live website search is not supported\nUse '%s search locations <query>' for location suggestions, '%s search saved' for session-backed saved-search state, or '%s search results-url' for validated result-page filters", cmd.Root().Name(), cmd.Root().Name(), cmd.Root().Name()))
			}
			return runLocalSearch(cmd, flags, query, resourceType, limit, dbPath)
		},
	}

	cmd.Flags().StringVar(&resourceType, "type", "", "Filter local FTS by resource type")
	cmd.Flags().IntVar(&limit, "limit", 50, "Maximum results to return")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/idealista-pp-cli/data.db)")

	localCmd := &cobra.Command{
		Use:   "local <query>",
		Short: "Full-text search across synced local SQLite data",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runLocalSearch(cmd, flags, args[0], resourceType, limit, dbPath)
		},
	}
	localCmd.Flags().StringVar(&resourceType, "type", "", "Filter local FTS by resource type")
	localCmd.Flags().IntVar(&limit, "limit", 50, "Maximum results to return")
	localCmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/idealista-pp-cli/data.db)")

	locationsCmd := &cobra.Command{
		Use:   "locations <query>",
		Short: "Look up website location suggestions",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runLocationSuggestSearch(cmd, flags, args[0])
		},
	}

	savedCmd := &cobra.Command{
		Use:   "saved",
		Short: "Inspect session-backed saved-search state",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runSavedSearchSummary(cmd, flags)
		},
	}

	cmd.AddCommand(localCmd)
	cmd.AddCommand(locationsCmd)
	cmd.AddCommand(savedCmd)
	cmd.AddCommand(newSearchResultsURLCmd(flags))
	return cmd
}

func runLocalSearch(cmd *cobra.Command, flags *rootFlags, query, resourceType string, limit int, dbPath string) error {
	if dryRunOK(flags) {
		return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
			"dry_run":      true,
			"query":        query,
			"resourceType": resourceType,
			"limit":        limit,
			"data_source":  "local",
		}, flags)
	}
	if dbPath == "" {
		dbPath = defaultDBPath("idealista-pp-cli")
	}

	db, err := store.OpenWithContext(cmd.Context(), dbPath)
	if err != nil {
		return fmt.Errorf("opening local database: %w\nRun 'idealista-pp-cli sync' first to populate the local database.", err)
	}
	defer db.Close()

	maybeEmitSyncHints(cmd, db, resourceType, flags.maxAge)

	var results []json.RawMessage
	switch resourceType {
	case "":
		seen := make(map[string]bool)
		partial, searchErr := db.Search(query, limit)
		if searchErr != nil {
			return fmt.Errorf("search resources_fts failed: %w", searchErr)
		}
		for _, r := range partial {
			key := string(r)
			if !seen[key] {
				seen[key] = true
				results = append(results, r)
			}
		}
	default:
		results, err = db.Search(query, limit)
	}
	if err != nil {
		return fmt.Errorf("search failed: %w", err)
	}

	reason := "user_requested"
	if flags.dataSource == "auto" {
		reason = "api_unreachable"
	}
	prov := localProvenance(db, "search", reason)
	return outputSearchResults(cmd, flags, results, limit, prov)
}

func runLocationSuggestSearch(cmd *cobra.Command, flags *rootFlags, query string) error {
	c, err := flags.newClient()
	if err != nil {
		return err
	}
	data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "pt", false, "/pt/locationsSuggest/sale/home", map[string]string{
		"searchField": query,
	}, nil, io.Discard)
	if err != nil {
		return classifyAPIError(err, flags)
	}
	var matches any
	if err := json.Unmarshal(data, &matches); err != nil {
		return err
	}
	payload := map[string]any{
		"query":   query,
		"matches": matches,
	}
	return outputWebsiteSearchPayload(cmd, flags, payload, prov)
}

func runSavedSearchSummary(cmd *cobra.Command, flags *rootFlags) error {
	c, err := flags.newClient()
	if err != nil {
		return err
	}
	data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "pt", false, "/pt/home/user-searches", nil, nil, io.Discard)
	if err != nil {
		return classifyAPIError(err, flags)
	}
	payload, err := summarizeSavedSearchPayload(data)
	if err != nil {
		return err
	}
	return outputWebsiteSearchPayload(cmd, flags, payload, prov)
}

func summarizeSavedSearchPayload(data json.RawMessage) (map[string]any, error) {
	var root any
	if err := json.Unmarshal(data, &root); err != nil {
		return nil, err
	}
	summary := map[string]any{}
	if v, ok := findPreferredScalar(root, []string{"lastSearchName", "lastSearch", "searchName", "name", "title"}); ok {
		summary["last_search_name"] = v
	}
	if v, ok := findPreferredScalar(root, []string{"searchUrl", "url"}); ok {
		summary["search_url"] = v
	}
	if v, ok := findPreferredScalar(root, []string{"totalAds", "adsCount", "totalResults", "count"}); ok {
		summary["total_ads"] = v
	}
	if v, ok := findPreferredScalar(root, []string{"canBeSaved", "canSave", "saveable", "savable", "isSaveable"}); ok {
		summary["can_be_saved"] = v
	}
	if len(summary) == 0 {
		summary["message"] = "Saved-search payload did not expose known operator summary fields; use 'pt list-user-searches' for the raw website response"
	}
	return summary, nil
}

func findPreferredScalar(root any, keys []string) (any, bool) {
	for _, key := range keys {
		if value, ok := findScalarByKey(root, strings.ToLower(key)); ok {
			return value, true
		}
	}
	return nil, false
}

func findScalarByKey(root any, key string) (any, bool) {
	switch v := root.(type) {
	case map[string]any:
		for k, child := range v {
			if strings.EqualFold(k, key) {
				if scalar, ok := normalizeScalar(child); ok {
					return scalar, true
				}
			}
		}
		for _, child := range v {
			if scalar, ok := findScalarByKey(child, key); ok {
				return scalar, true
			}
		}
	case []any:
		for _, child := range v {
			if scalar, ok := findScalarByKey(child, key); ok {
				return scalar, true
			}
		}
	}
	return nil, false
}

func normalizeScalar(v any) (any, bool) {
	switch value := v.(type) {
	case string:
		if strings.TrimSpace(value) == "" {
			return nil, false
		}
		return value, true
	case float64, bool, int, int64:
		return value, true
	default:
		return nil, false
	}
}

func outputWebsiteSearchPayload(cmd *cobra.Command, flags *rootFlags, payload any, prov DataProvenance) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
		filtered := data
		if flags.selectFields != "" {
			filtered = filterFields(filtered, flags.selectFields)
		} else if flags.compact {
			filtered = compactFields(filtered)
		}
		wrapped, wrapErr := wrapWithProvenance(filtered, prov)
		if wrapErr != nil {
			return wrapErr
		}
		return printOutput(cmd.OutOrStdout(), wrapped, true)
	}
	printProvenance(cmd, 1, prov)
	return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
}

// isNilOrEmpty checks whether a JSON object has nil or empty values for
// common identifier fields (title, name, identifier, id).
// Also checks nested "document" objects for search result wrappers.
func isNilOrEmpty(raw json.RawMessage) bool {
	var obj map[string]interface{}
	if err := json.Unmarshal(raw, &obj); err != nil {
		return true
	}
	// Check top-level fields
	for _, key := range []string{"title", "name", "identifier", "id"} {
		if v, ok := obj[key]; ok {
			if v == nil {
				continue
			}
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				return false
			}
			// Non-string, non-nil value (e.g. numeric ID) — keep it
			if _, ok := v.(string); !ok {
				return false
			}
		}
	}
	// Check nested "document" for search result wrappers like {score, document: {name, ...}}
	if doc, ok := obj["document"]; ok {
		if docMap, ok := doc.(map[string]interface{}); ok {
			for _, key := range []string{"title", "name", "identifier", "id", "slug"} {
				if v, ok := docMap[key]; ok && v != nil {
					if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
						return false
					}
					if _, ok := v.(string); !ok {
						return false
					}
				}
			}
		}
	}
	// If the object has a "score" field, it's likely a search result — keep it
	if _, ok := obj["score"]; ok {
		return false
	}
	return true
}

// extractSearchResults unwraps API search responses by checking common envelope paths.
func extractSearchResults(data json.RawMessage) []json.RawMessage {
	// Try direct array first
	var items []json.RawMessage
	if json.Unmarshal(data, &items) == nil {
		return items
	}
	// Try common wrapper paths: data, results, items
	var wrapped map[string]json.RawMessage
	if json.Unmarshal(data, &wrapped) == nil {
		for _, key := range []string{"data", "results", "items", "records", "entries"} {
			if inner, ok := wrapped[key]; ok {
				if json.Unmarshal(inner, &items) == nil {
					return items
				}
			}
		}
	}
	// Return as single-item array
	return []json.RawMessage{data}
}

// outputSearchResults filters, counts, and outputs search results with provenance.
func outputSearchResults(cmd *cobra.Command, flags *rootFlags, results []json.RawMessage, limit int, prov DataProvenance) error {
	// Filter out entries with nil or empty identifier fields.
	filtered := make([]json.RawMessage, 0, len(results))
	for _, r := range results {
		if !isNilOrEmpty(r) {
			filtered = append(filtered, r)
		}
	}
	results = filtered

	// Enforce limit across aggregated results.
	if len(results) > limit {
		results = results[:limit]
	}

	jsonMode := flags.asJSON || !isTerminal(cmd.OutOrStdout())

	// JSON mode always emits a valid envelope, including on no matches —
	// agents pipe stdout through json.loads / jq and need parseable output
	// regardless of result count. The filtered slice is built via make
	// above, so it's non-nil even when empty; json.Marshal renders that
	// as `[]` rather than `null`.
	if jsonMode {
		data, err := json.Marshal(results)
		if err != nil {
			return err
		}
		wrapped, err := wrapWithProvenance(data, prov)
		if err != nil {
			return err
		}
		return printOutput(cmd.OutOrStdout(), wrapped, true)
	}

	if len(results) == 0 {
		fmt.Fprintf(cmd.ErrOrStderr(), "No results (source: %s)\n", prov.Source)
		return nil
	}

	printProvenance(cmd, len(results), prov)
	for _, r := range results {
		fmt.Fprintln(cmd.OutOrStdout(), string(r))
	}
	return nil
}
